### ISSUE TITLE
Descripción de prototipos.

### ISSUE THREAD

**Issue by norman-ipn** [Az-PhoenixLeo/Yolotl#11]
@Yas631 La forma en que presentas los prototipos no parece ser muy técnica. La parte de la IA la presentas vagamente y parece una sección redactada a la carrera. le faltan referencias a las ilustraciones y hay ideas que están a medias.

**Comment by Yas631** [comment]
Que ideas esta a medias profesor? Debería incluir un capturas de codigo?
