### ISSUE TITLE
Problemas con la GUI

### ISSUE THREAD

**Issue by Yas631** [Az-PhoenixLeo/Yolotl#4]
Detecte un problema con la GUI.

- Dentro del primer nivel en la parte del tianguis, el disparo funciona pero fuera de esa escena el disparo deja de funcionar ya que su funcionalidad se vinculo con el controlador de diálogos y dado que ese controlador  no existe en otras escenas, Unity marca una excepción de referencia nula. Considero que arrastrar el controlador de diálogos a niveles donde no se utiliza para garantizar el funcionamiento de la GUI no seria lo más optimo ni lo correcto. Favor de corregir esa parte.

- En caso de modificar la GUI, favor de verificar que los cambios realizados no afecten la funcionalidad de otras  escenas.

**Comment by norman-ipn** [comment]
En este momento el Reporte de TT1 tiene prioridad, @Az-PhoenixLeo atiende este **issue** en cuanto termines las secciónes del reporte técnico.

**Comment by azmeruq** [comment]
listo! :v
